pipeline:
  kubectl:
    image: gcr.io/pl-infra/kluster-toolbox
    commands:
      - kubectl config set-cluster localkube-image --server=https://minikube:8443
      - kubectl config set-context localkube-image --cluster=localkube-image
      - kubectl config use-context localkube-image
      - sleep 30
      - kubectl get componentstatus
      - kubectl get no
services:
  minikube:
    environment:
      - KUBERNETES_VERSION=1.8.0
    image: whindes/alpine-minikube:22.3
    privileged: true
    commands:
      - dockerd-entrypoint.sh dockerd-cmd.sh &
      - sleep 5
      - minikube start
      - sleep 20
      - ps auxf
      - kubectl get componentstatus
      - kubectl get nodes
